### ISSUE TITLE
Error CS0246: The type or namespace name 'RubyTextMeshPro' could not be found

### ISSUE THREAD

**Issue by quabug** [ls9512/UTween#1]
1. Install from openupm
2. open Unity editor.
3. ![image](https://user-images.githubusercontent.com/683655/112090594-cd5ed480-8bce-11eb-86d6-e9a442404012.png)

Have to install 'RubyTextMeshPro' to eliminate errors?

Suggestion:
1. Consider use "[Version Defines](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html)" from assembly and wrap relative code inside a specific define?
2. ~Move extensions into [sample directory](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/), a directory ending with '\~'.~ (seems like its already in a sample directory but failed to rename with '~')

**Comment by ls9512** [comment]
> 1. Install from openupm
> 2. open Unity editor.
> 3. ![image](https://user-images.githubusercontent.com/683655/112090594-cd5ed480-8bce-11eb-86d6-e9a442404012.png)
> 
> Have to install 'RubyTextMeshPro' to eliminate errors?
> 
> Suggestion:
> 
> 1. Consider use "[Version Defines](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html)" from assembly and wrap relative code inside a specific define?
> 2. ~Move extensions into [sample directory](https://forum.unity.com/threads/samples-in-packages-manual-setup.623080/), a directory ending with '~'.~ (seems like its already in a sample directory but failed to rename with '~')

Thanks for your feedback and suggestions, I will fix this problem as soon as possible.
